### ISSUE TITLE
Bug: First Call takes > 10 Seconds

### ISSUE THREAD

**Issue by bbjoern** [moberwasserlechner/capacitor-sms#9] opened 2020-08-28 12:56 UTC
### Capacitor version:

Run `npx cap doctor`:

```
Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/ios 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed
```

### Library version:

- 2.0.0

### Your Plugin Configuration

```typescript
No Special Config.. just default setup
```

### Affected Platform(s):

- iOS

### Current Behavior

First start of native sms window takes min 10 sec. 
The following call the calls are under 1 sec.

### Expected Behavior

First start of native sms window should be same as the following starts (~1 sec)

### Sample Code or Sample Application Repo

                            Plugins.SmsManager.send({
                                numbers: [this.inputContact.phone],
                                text: 'Dear ' + this.inputContact.name + ',',
                              }).then(() => {
                                this.openContactRequestModal();
                              }).catch(error => {
                                  // see error codes below
                                  if (error.message !== 'SEND_CANCELLED') {
                                      // show toast with error message
                                      console.log(error.message);
                                  }
                              });

### Other Information

Tested on iPhone 8 13.6.1

**Comment by JayHong705** [comment] 2021-01-19 03:30
Our team also has experienced this and would like to ask for fixing this issue since it is critical to our users. They would feel this sms function is originally not working after trying first time and not keep using this function. Our team appreciates you for managing this plugin. Thanks.

**Comment by moberwasserlechner** [comment] 2021-01-26 16:31
I can confirm the bug on iOS `14.3`. In my case the sms app needs 2-3 tries until it opens. 

I can't give a exact timeline but I hope to have it fixed within the next 2 weeks.

**Comment by moberwasserlechner** [comment] 2021-02-23 12:20
This issue is not really obvious because I'm do the same as all tutorials. Despite that the start is slow but it seems that there is little I can do as Apple is in control of the whole process.

The links below are for my further debugging:

https://forums.xamarin.com/discussion/176475/xamarin-ios-sms-multiple-recipients

I need to try if it is possible to set the recipients after the messaging app was opened, as this is the source of slow down according to forum entries.

If that does not help a loading information for the users is the only workaround I can think about.

**Comment by charles-sunflower** [comment] 2021-05-30 01:34
any updates on this?

**Comment by chrum** [comment] 2021-11-08 10:57
Hey, 

I think that change provided in this PR https://github.com/moberwasserlechner/capacitor-sms/pull/13 should help.

Until PR is verified/accepted/merged you can test/use it by installing it from my repo like:
```
npm install https://github.com/chrum/capacitor-sms --save
```

**Comment by moberwasserlechner** [comment] 2022-04-13 11:36
I've release a new version but I would like to ask if you could test it properly as I have no easy way to do it right now. I'll try to push release faster if a PR was merged. thx.

**Closed by moberwasserlechner** 2022-04-13 11:36 UTC
Labels: bug, ios
